package com.test.entites;

// Generated 2016-7-22 16:17:51 by Hibernate Tools 3.4.0.CR1

/**
 * Menu generated by hbm2java
 */
public class Menu implements java.io.Serializable {

	private Integer menuid;
	private int parentid;
	private String name;
	private String url;
	private String description;
	private String target;
	private String style;
	private boolean isfolder;
	private boolean isopen;
	private int listorder;

	public Menu() {
	}

	public Menu(int parentid, String name, String url, String description,
			String target, String style, boolean isfolder, boolean isopen,
			int listorder) {
		this.parentid = parentid;
		this.name = name;
		this.url = url;
		this.description = description;
		this.target = target;
		this.style = style;
		this.isfolder = isfolder;
		this.isopen = isopen;
		this.listorder = listorder;
	}

	public Integer getMenuid() {
		return this.menuid;
	}

	public void setMenuid(Integer menuid) {
		this.menuid = menuid;
	}

	public int getParentid() {
		return this.parentid;
	}

	public void setParentid(int parentid) {
		this.parentid = parentid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getTarget() {
		return this.target;
	}

	public void setTarget(String target) {
		this.target = target;
	}

	public String getStyle() {
		return this.style;
	}

	public void setStyle(String style) {
		this.style = style;
	}

	public boolean isIsfolder() {
		return this.isfolder;
	}

	public void setIsfolder(boolean isfolder) {
		this.isfolder = isfolder;
	}

	public boolean isIsopen() {
		return this.isopen;
	}

	public void setIsopen(boolean isopen) {
		this.isopen = isopen;
	}

	public int getListorder() {
		return this.listorder;
	}

	public void setListorder(int listorder) {
		this.listorder = listorder;
	}

}
